uploads = []
generated = []

[[outputs]]
id = "9khr7Nh71CvY-pKqMhryJ"
uri = "file://oyo-plast-backup-20260407.tar.gz"
type = "unspecified"
title = "نسخة احتياطية — ملفات المشروع الكاملة"

[[outputs]]
id = "iJDpNWwnThRO5MZR4NfWS"
uri = "file://oyoplast_backup_2026-04-07.tar.gz"
type = "unspecified"
title = "نسخة احتياطية كاملة - أويو بلاست (2026-04-07)"
