import React from 'react';
import { Amplify } from 'aws-amplify';
import { Authenticator } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';
import awsExports from '../../aws-exports';

// Configure Amplify with the generated aws-exports (placeholder file provided).
Amplify.configure(awsExports as any);

/**
 * Login component using Amplify UI Authenticator.
 * Usage: import Login from 'src/components/Auth/Login' and render it where you want the sign-in flow.
 * After you provision Auth in Amplify, replace the contents of src/aws-exports.ts with the values
 * generated by Amplify (or export them into environment variables as you prefer).
 */
export default function Login(): JSX.Element {
  return (
    <div style={{ display: 'flex', justifyContent: 'center', padding: 24 }}>
      <div style={{ width: 420 }}>
        <Authenticator>
          {({ signOut, user }) => (
            <main>
              <h1 style={{ fontSize: 20, marginBottom: 12 }}>مرحبًا بك في متجر OYO Plast</h1>
              <p>تم تسجيل الدخول باسم: {user?.username}</p>
              <button onClick={signOut}>تسجيل الخروج</button>
            </main>
          )}
        </Authenticator>
      </div>
    </div>
  );
}
